export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_PROFILES_REQUEST = 'USER_PROFILES_REQUEST';
export const USER_PROFILES_SUCCESS = 'USER_PROFILES_SUCCESS';
export const USER_PROFILES_FAIL = 'USER_PROFILES_FAIL';
